
<div id="top" class="container">
<div id="form-container">


		<article><strong>Slavens Realty</strong> is a leader in the Next Generation of Real Estate offices. Our mission is to efficiently provide unmatched service to our agents while offering the highest possible commission. In fact we consider our agents to be our customers. Here&rsquo;s why joining our team would be one of the best moves you could make in your Real Estate Career.</article>

	    <ul id="agent_benefits">
		   <li>No Monthly Fees</li>
		   <li>No Start Up Fees</li>
		   <li>Part Time OK</li>
		   <li>Incremental Training Program</li>
		   <li>Free Marketing Support</li>
		   <li>No Quotas</li>
		   <li>Paid straight from Escrow</li>
		   <li>No mandatory meetings</li>
		   <li>Work from home</li>

		    <li>On Line Training Library</li>

		    <li>Access your files/transactions 24/7 via Cloud Technology</li>

		    <li>Using the latest California Association of Realtor Software, Dynamic forms and checklists are generated by our system based on your transaction.</li>

		    <li>Receive email notifications for tasks due.</li>

		    <li>** Agents are responsible for their own association and MLS fees.</li>

	    </ul>


		<h3><span class="label label-default">REQUEST MORE INFORMATION</span></h3>

		<!-- codeignitor errors -->
		<?php echo validation_errors(); ?>

		<?php echo form_open(''); ?>
		<?php echo "soource is "; ?>
			<div class="form-group">

		    	<label for="firstname">First Name</label>

		    	<input required type="text" name="first_name" class="form-control" placeholder="First Name">

		  	</div>

		  	<div class="form-group">

		    	<label for="lastname">Last Name</label>

		    	<input required type="text" name="last_name" class="form-control" placeholder="Last Name">

		  	</div>

		  	<div class="form-group">

		    	<label for="phone">Phone</label>

		    	<input type="text" name="phone" class="form-control" placeholder="Phone">

		  	</div>

		    <div class="form-group">

			    <label for="email">Email address</label>

			    <input required type="email" class="form-control" name="blue" placeholder="Enter email">

		    </div>

		    <div style="display:none;">
		    	<label for="email">Leave this blank if you're human</label>
		    	<input type="text" name="email">
		    </div>

		    <div class="form-group">

		    	<label for="licensed">Do you have a Real Estate License?</label>

			  	<div class="radio">

				  <label>

				    <input type="radio" name="license_status" id="license_status1" value="1" >

				    Yes

				  </label>

				</div>

				<div class="radio">

				  <label>

				    <input type="radio" name="license_status" id="license_status2" value="2">

				    No

				  </label>

				</div>

		    </div>

		    <div style="display: none" id="license_number" class="form-group">

		    	<label for="phone">License Number</label>
		    	<input title="Enter CA BRE License Number" type="text" name="license_number" class="form-control" >

		  	</div>	

			<!-- <div class="form-group">

				<img id="captcha" src="/securimage/securimage_show.php" alt="CAPTCHA Image" />

				<input required type="text" name="captcha_code" size="10" maxlength="6" />

				<a href="#" onclick="document.getElementById('captcha').src = '/securimage/securimage_show.php?' + Math.random(); return false">New Image</a>

			</div> -->
			<input type="hidden" value="<php echo" name="source_short_name">


		   <!-- craigslist.. need to update -->
		   <input type="hidden" name="source" class="form-control" value="<?php echo $source; ?>">

		   <br />
		   <br />
		  <button type="submit" name="submit" class="btn btn-primary">Submit</button>

		</form>

</div><!-- form-container -->
<br />
<br />

<div class="fixed_bottom inverse_text"><a href="top"><span class="glyphicon glyphicon-circle-arrow-up"></span>&nbsp;top</a></div>
</div>

<script>
$('#license_status1').click(function()
{
	$('#license_number').show(100);
});

$('#license_status2').click(function()
{
	$('#license_number').hide(100);
});
</script>